### ISSUE TITLE
Message not being generated for special weather statements

### ISSUE THREAD

**Issue by ajbelayer** [K2IE/noaacap#4]
There is special weather statement out for the county (MNC017) I have configured but noaacap is not reporting it, I am just starting with noaacap so probably something I am doing wrong.  I have attached a curl of the xml file showing the statement, my config, related /var/log/messages, and the noaacap.db file (seems relevant).
[message.log](https://github.com/K2IE/noaacap/files/6840501/message.log)
[Archive.zip](https://github.com/K2IE/noaacap/files/6840507/Archive.zip)

Any help would be appreciated.

**Comment by K2IE** [comment]
noaacap does not alert on Special Weather Statements.  Expect to receive alerts on messages coded as a Watch, Warning, or Advisory.
