### ISSUE TITLE
Noaacap no longer working

### ISSUE THREAD

**Issue by k8tek** [K2IE/noaacap#6]
NOAA changed their cap feed and now none of your alerts work.

**Comment by K2IE** [comment]
Please provide a pointer to the specific changes that yiou refer to.

**Comment by k8tek** [comment]
NWS Common Alerting Protocol (CAP) Users,

This is a friendly reminder that NWS CAP v1.1 is being terminated. NWS supports and continues production of CAP v1.2. Please see the following two links for the latest announcements. I've also provided a brief summary below each link.
 
[NWS Alerts Atomic Syndication Format (ATOM) Data Changes: Effective on or about January 31, 2024](https://www.weather.gov/media/notification/pdf_2023_24/scn23-122_atom_feed_transition.pdf)
Describes NWS transition of the NWS Alerts ATOM feed on or about January 31, 2024 to utilizing CAP 1.2 data provided by the NWS API at api.weather.gov.  Users that pull data from alerts.weather.gov via tools such as curl or wget may need to make changes to ensure continuity of service. 

[alerts.weather.gov Version 2.3.0 Upgrade: Effective on or about February 14, 2024](https://www.weather.gov/media/notification/pdf_2023_24/scn23-121_alerts_2.3.0_aaa.pdf)
Describes NWS implementation of a new version of alerts.weather.gov on or about February 14, 2024, at which time, the dissemination by NWS of products formatted with CAP v1.1 will be terminated.  As a result, the user interface at alerts.weather.gov will be updated and will begin using the CAP 1.2 formatted data provided by the NWS Application Programming Interface (API) at api.weather.gov.

**Comment by k8tek** [comment]
Im specifically referring to your DAPNET rubicies no longer working

**Comment by K2IE** [comment]
noaacap has been updated to be CAP 1.2 compliant.  Tickets with regard to DAPNET should normally be opened via http://hampager.de.  I will look at that issue next.

**Comment by K2IE** [comment]
Fixed in noaacap v 1.1
